fragment_tsv: "/oak/stanford/groups/engreitz/Users/atan5133/data/stitziel_multiome/stitziel_cell_frag_counts.tsv"
output_folder: "/oak/stanford/groups/engreitz/Users/atan5133/data/stitziel_multiome/cell_type_fragment_files"
chrom_bed: "GRCh38_EBV.no_alt.chrom.sizes.tsv.bed"